name: Deploy to gh-pages

on:
  push:
    branches:
      - master # change this to the branch you want to trigger the build on

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "#{HOMEPAGE}"
          replace: "https://mahc30.github.io/portfolio/"
          include: "./portfolio-app"
          regex: true
          
      - name: Install dependencies
        run: npm install
        working-directory: ./portfolio-app

      - name: Build React app
        run: CI=false npm run build
        working-directory: ./portfolio-app

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./portfolio-app/build
          publish_branch: gh-pages
